name: CI - Tests, Lint & Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # adapte si besoin

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black bandit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check code formatting with Black
      run: |
        black --check .

    # - name: Run Bandit security checks
    #   run: |
    #     bandit -r . -x tests

    - name: Run tests with Pytest
      run: |
        pytest tests